apiVersion: apps/v1
kind: Deployment
metadata:
  name: con2-deployment
  labels:
    app: k8s-con2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-con2
  template:
    metadata:
      labels:
        app: k8s-con2
    spec:
      containers:
        - name: k8s-con2
          image: northamerica-northeast1-docker.pkg.dev/cloud-k8s-427803/k8s-assignment/k8s-con2
          ports:
            - containerPort: 2000
          env:
            - name: PORT
              value: "2000"
            - name: FILE_DIRECTORY
              value: "/khush_PV_dir"
          volumeMounts:
            - mountPath: /khush_PV_dir
              name: persistent-volume
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: k8s-assignment-pv-claim   