apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-assignment-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi