apiVersion: v1
kind: Service
metadata:
  name: con1-service
spec:
  selector:
    app: k8s-con1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: con2-service
spec:
  selector:
    app: k8s-con2
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 2000